version: "3.8"
services:
  db:
    image: postgres:14.3
    container_name: db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  pgadmin:
    image: adminer:4.8.1
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  webserver:
    container_name: webserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env
